# Generated by Django 2.2 on 2019-04-30 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_directions', models.IntegerField(default=3)),
                ('number_of_plays', models.IntegerField(blank=True)),
                ('min_plays', models.IntegerField(blank=True)),
                ('min_hits_in_seq', models.IntegerField(blank=True)),
                ('sequence', models.CharField(blank=True, max_length=255)),
                ('read_seq', models.BooleanField()),
                ('plays_to_relax', models.IntegerField(default=0)),
                ('play_pause', models.BooleanField()),
                ('play_pause_key', models.CharField(blank=True, max_length=10)),
                ('animation_time', models.FloatField(default=1.0)),
                ('score_board', models.BooleanField()),
                ('final_score_board', models.CharField(choices=[('long', 'Long'), ('short', 'Short'), ('none', 'None')], max_length=5)),
                ('game_type', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoalkeeperGame',
            fields=[
                ('game_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.Game')),
                ('phase', models.IntegerField()),
                ('depth', models.IntegerField()),
                ('seq_step_det_or_prob', models.CharField(blank=True, max_length=255)),
                ('show_history', models.BooleanField()),
                ('send_markers_eeg', models.CharField(blank=True, max_length=30)),
                ('port_eeg_serial', models.CharField(blank=True, max_length=30)),
            ],
            bases=('game.game',),
        ),
        migrations.CreateModel(
            name='MemoryGame',
            fields=[
                ('game_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.Game')),
                ('phase', models.IntegerField()),
            ],
            bases=('game.game',),
        ),
        migrations.CreateModel(
            name='WarmUp',
            fields=[
                ('game_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.Game')),
            ],
            bases=('game.game',),
        ),
        migrations.CreateModel(
            name='GameConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('is_public', models.BooleanField()),
                ('name', models.CharField(max_length=100)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.Institution')),
            ],
            options={
                'verbose_name': 'Game configuration',
                'verbose_name_plural': 'Game configurations',
                'ordering': ('name',),
                'unique_together': {('institution', 'code')},
            },
        ),
        migrations.AddField(
            model_name='game',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.GameConfig'),
        ),
        migrations.AddField(
            model_name='game',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.Level'),
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=5)),
                ('prob_event_0', models.FloatField()),
                ('prob_event_1', models.FloatField()),
                ('goalkeeper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.GoalkeeperGame')),
            ],
        ),
    ]
