# Generated by Django 2.2 on 2019-06-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='number_of_directions',
            field=models.IntegerField(choices=[(2, '2 - left and right'), (3, '3 - left, center and right')],
                                      default=3),
        ),
        migrations.AlterField(
            model_name='game',
            name='number_of_plays',
            field=models.IntegerField(default=1),
        ),
    ]
