# Generated by Django 2.2 on 2019-06-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='is_context',
            field=models.BooleanField(null=True),
        ),
    ]
