# Generated by Django 2.2 on 2019-06-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameconfig',
            name='is_public',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=3),
        ),
    ]
