# Generated by Django 2.2 on 2019-06-05 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_is_public_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameconfig',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='gameconfig',
            name='is_public',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=3, verbose_name='Is it public?'),
        ),
        migrations.AlterField(
            model_name='gameconfig',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.Level', verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='gameconfig',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
