# Generated by Django 2.2 on 2019-06-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_context_delete_cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalkeepergame',
            name='depth',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
