# Generated by Django 2.2.1 on 2019-06-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_depth_null_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='center_key',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='left_key',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='right_key',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
