# Generated by Django 2.2 on 2019-06-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20190626_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='min_hits',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='min_hits_in_seq',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='number_of_plays',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='plays_to_relax',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
